### ISSUE TITLE
RegisterForm.Designer.cs compilation errors

### ISSUE THREAD

**Issue by ghost** [skiffaw/OrbisDbgUI#3]
It appears that a fresh clone gets compiler errors. Commenting out lines 130,  596, and 607 fixes the issue. This issue was introduced in #1

**Comment by ghost** [comment]
I must have not pushed something important because I made sure it compiled.
